# Generated by Django 5.1.4 on 2024-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_delete_productdiscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts', models.ManyToManyField(to='system.discount')),
                ('products', models.ManyToManyField(to='system.product')),
            ],
        ),
    ]
